name: Publish oomie to Arti

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
  DEPLOY_IMAGE_NAME: kalamaja-bootstrapper
  DEPLOY_REGISTRY_URL: docker.tw.ee

jobs:
  publish-docker-local:
    name: Upload to docker-local
    runs-on: [self-hosted, production, large]
    container: docker.tw.ee/k8s-deployer:3
    outputs:
      tag: ${{ steps.docker.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Add repo as safe directory
        run: |
          git config --global --add safe.directory "$(pwd)"
      - name: Set version tag env
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Upload docker image
        id: docker
        run: k8s-deployment docker-build-multiarch-push
        env:
          DEPLOY_IMAGE_NAME: oomie
          DEPLOY_REGISTRY_URL: docker.tw.ee
          DEPLOY_USE_SEMANTIC_VERSIONING: True
          DEPLOY_IMAGE_VERSION: ${{ env.VERSION }}
      - name: Output version
        run: |
          echo ${{ steps.docker.outputs.tag }} >> $GITHUB_STEP_SUMMARY

  promote-to-docker-release:
    name: Promote to docker-release
    runs-on: [self-hosted, production, medium]
    container: docker.tw.ee/k8s-deployer:3
    needs:
      - publish-docker-local
    steps:
      - name: Promote docker image
        run: k8s-deployment trigger-image-promotion
        env:
          DEPLOY_IMAGE_NAME: oomie
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
